services:
  backend:
    build:
      context: ./django_backend
      dockerfile: Dockerfile

    environment:
      - CUDA_VISIBLE_DEVICES=""
      - TF_CPP_MIN_LOG_LEVEL=2
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend
