# Generated by Django 5.2.6 on 2025-09-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExoPlanetData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planet_name', models.CharField(max_length=100)),
            ],
        ),
    ]
