# Generated by Django 5.2.6 on 2025-10-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exoplanetdata',
            name='confidence',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
